<head>
 <meta charset='utf-8'>
</head>

theme: jekyll-theme-cayman
title: TRIP TO DJIBOUTI &#2708; LEARN FRENCH	
description: An example on how to use GitHub Pages
github:
  page2: html.html
  page3: sentences.html
  page4: idioms.html
  page5: exercises.html
