theme: jekyll-theme-cayman
title: TRIP TO DJIBOUTI ✈ LEARN FRENCH	
description: A website to help you make the most of your trip to Djibouti
github:
  page2: html.html
  page3: sentences.html
  page4: idioms.html
  page5: exercises.html
  page6: furtherstudy.html
