theme: jekyll-theme-cayman
title: TRIP TO DJIBOUTI ✈ LEARN FRENCH	
description: A website to help you make the most of your trip to Djibouti
github:
  page2: about.html
  page3: vocabulary.html
  page4: sentences.html
  page5: phrases.html
  page6: furtherstudy.html
