theme: jekyll-theme-cayman
title: TRIP TO DJIBOUTI ✈ LEARN FRENCH	
description: An example on how to use GitHub Pages
github:
  page2: html.html
  page3: sentences.html
  page4: idioms.html
  page5: exercises.html
